spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5430/themeparkdb
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: order_service

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

  kafka:
    bootstrap-servers: localhost:8088
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  mq:
    exchange: stock.direct
    routingKey: stock.decrease
    queue: stock.decrease.q         # ★ 추가
    dlx: stock.dlx                  # ★ 추가 (Dead Letter Exchange 이름)
    dlq: stock.decrease.dlq

    # ★ 결과 이벤트(새로 추가)
    result-exchange: stock.result.direct
    result-queue: order.stock.result.q
    result-routing-keys:
      - stock.decreased
      - stock.rejected

server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  tracing:
    sampling:
      probability: 1.0
    enabled: true
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans

toss:
  secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
  clientKey: test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm
